projectType: extension
additionalTestConfigs:
  postgresql:
    mavenAdditionalArgs: "-Dpostgresql -DminVersion=4.3.0"
  mysql:
    mavenAdditionalArgs: "-Dmysql -DminVersion=4.3.0"
  mssql:
    mavenAdditionalArgs: "-Dmssql -DminVersion=4.3.0"
  oracle:
    mavenAdditionalArgs: "-Doracle -DminVersion=4.3.0"
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.3.0 -Doracle
  jdk17:
      testJdkTool: OPEN-JDK17
      mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0 -DruntimeVersion=4.6.0-rc3 -Doracle