projectType: extension
additionalTestConfigs:
  postgresql:
    mavenAdditionalArgs: "-Dpostgresql -DminVersion=4.3.0"
  mysql:
    mavenAdditionalArgs: "-Dmysql -DminVersion=4.3.0"
  mssql:
    mavenAdditionalArgs: "-Dmssql -DminVersion=4.3.0"
  oracle:
    mavenAdditionalArgs: "-Doracle -DminVersion=4.3.0"