projectType: extension
additionalTestConfigs:
  postgresql:
    mavenAdditionalArgs: "-Dpostgresql"
  derby:
    mavenAdditionalArgs: "-Dderby"
  mysql:
    mavenAdditionalArgs: "-Dmysql"
  mssql:
    mavenAdditionalArgs: "-Dmssql"
  oracle:
    mavenAdditionalArgs: "-Doracle"