package org.mule.extension.db.internal.domain.autogeneratedkey;

import static org.mule.runtime.extension.api.annotation.param.display.Placement.ADVANCED_TAB;
import org.mule.runtime.extension.api.annotation.param.Optional;
import org.mule.runtime.extension.api.annotation.param.Parameter;
import org.mule.runtime.extension.api.annotation.param.display.Placement;

import java.util.List;

/**
 * Parameters to configure if and how should keys be auto generated
 *
 * @since 1.0
 */
public class AutoGenerateKeysAttributes implements org.mule.db.commons.internal.domain.autogeneratedkey.AutoGenerateKeysAttributes {

    /**
     * Indicates when to make auto-generated keys available for retrieval.
     */
    @Parameter
    @Optional(defaultValue = "false")
    @Placement(tab = ADVANCED_TAB, order = 1)
    private boolean autoGenerateKeys = false;

    /**
     * List of column indexes that indicates which auto-generated keys to make available for retrieval.
     */
    @Parameter
    @Optional
    @Placement(tab = ADVANCED_TAB, order = 2)
    private List<Integer> autoGeneratedKeysColumnIndexes;

    /**
     * List of column names that indicates which auto-generated keys should be made available for retrieval.
     */
    @Parameter
    @Optional
    @Placement(tab = ADVANCED_TAB, order = 3)
    private List<String> autoGeneratedKeysColumnNames;

    public boolean isAutoGenerateKeys() {
        return autoGenerateKeys;
    }

    public List<Integer> getAutoGeneratedKeysColumnIndexes() {
        return autoGeneratedKeysColumnIndexes;
    }

    public List<String> getAutoGeneratedKeysColumnNames() {
        return autoGeneratedKeysColumnNames;
    }

}
